server:
  port: 8080

spring:
 application:
    name: ruiji
 datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ruiji
    username: root
    password: 123456
 servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
 data:
  redis:
   host: 192.168.164.182
   port: 6379
   password: 123456
   database: 0
   lettuce:
    pool:
     max-active: 8        # 保持不变，但确保使用的是正确版本
     max-wait: 1ms
     max-idle: 4
     min-idle: 0
 cache:
  redis:
   time-to-live: 600000
 mail:
    host: smtp.qq.com
    port: 587  # 或 465（SSL）
    username: 2714156899@qq.com  # 你的QQ邮箱
    password: "ycznndddlbmwdhac"  # 授权码，不是QQ密码
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: false  # 如果使用465端口
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

mybatis:
 configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 添加此行导入自定义配置
spring.config.import: optional:ruiji
ruiji:
  path: D:/internet-of-t/JAVA_Web/stage6/ruiji/src/main/resources/img/
